# Generated by Django 4.2.4 on 2023-08-25 17:21

import api.helpers
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=api.models.upload)),
                ('datestamp', models.CharField(blank=True, default=api.helpers.getdate, max_length=225, null=True)),
                ('timestamp', models.CharField(blank=True, default=api.helpers.gettime, max_length=225, null=True)),
                ('total_number_of_students', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('roll_number', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=225, null=True)),
            ],
        ),
    ]
