# Generated by Django 4.1.7 on 2023-09-22 08:56

import api.helpers
import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=api.models.upload_group_photo)),
                ('datestamp', models.CharField(blank=True, default=api.helpers.getdate, max_length=225, null=True)),
                ('timestamp', models.CharField(blank=True, default=api.helpers.gettime, max_length=225, null=True)),
                ('total_number_of_students', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_student_image)),
                ('image2', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_student_image)),
                ('roll_number', models.IntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=225, null=True)),
                ('year', models.IntegerField(blank=True, default=None, null=True)),
                ('course', models.CharField(blank=True, choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], default=None, max_length=225, null=True)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EE', 'EE'), ('ME', 'ME'), ('MEMS', 'MEMS'), ('CE', 'CE')], default=None, max_length=225, null=True)),
            ],
        ),
    ]
