# Generated by Django 4.1.7 on 2023-09-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('MEMS', 'MEMS'), ('CE', 'CE'), ('ME', 'ME'), ('EE', 'EE'), ('CSE', 'CSE')], default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
