# Generated by Django 4.1.7 on 2023-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_branch_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('MEMS', 'MEMS'), ('CSE', 'CSE'), ('ME', 'ME'), ('CE', 'CE'), ('EE', 'EE')], default=None, max_length=225, null=True),
        ),
    ]
