# Generated by Django 4.1.7 on 2023-09-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('ME', 'ME'), ('CSE', 'CSE'), ('MEMS', 'MEMS'), ('CE', 'CE'), ('EE', 'EE')], default=None, max_length=225, null=True),
        ),
    ]
