# Generated by Django 4.1.7 on 2023-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_student_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('EE', 'EE'), ('CE', 'CE'), ('ME', 'ME'), ('MEMS', 'MEMS')], default=None, max_length=225, null=True),
        ),
    ]
