# Generated by Django 4.1.7 on 2023-09-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphoto',
            name='course',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='groupphoto',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='groupphoto',
            name='students_present',
            field=models.ManyToManyField(to='api.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('ME', 'ME'), ('MEMS', 'MEMS'), ('CSE', 'CSE'), ('EE', 'EE'), ('CE', 'CE')], default=None, max_length=225, null=True),
        ),
    ]
