# Generated by Django 4.1.7 on 2023-09-23 05:54

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_groupphoto_course_groupphoto_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphoto',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_group_photo),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('CSE', 'CSE'), ('MEMS', 'MEMS'), ('ME', 'ME'), ('CE', 'CE')], default=None, max_length=225, null=True),
        ),
    ]
