# Generated by Django 4.2.4 on 2023-10-09 05:45

import api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_groupphoto_date_alter_groupphoto_datestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphoto',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='datestamp',
            field=models.CharField(blank=True, default=api.helpers.getdate, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('CSE', 'CSE'), ('CE', 'CE'), ('MEMS', 'MEMS'), ('ME', 'ME')], default=None, max_length=225, null=True),
        ),
    ]
