# Generated by Django 4.2.4 on 2023-10-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Done', 'Done'), ('Error', 'Error')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('CSE', 'CSE'), ('MEMS', 'MEMS'), ('CE', 'CE'), ('ME', 'ME')], default=None, max_length=225, null=True),
        ),
    ]
