# Generated by Django 4.1.7 on 2023-10-17 19:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_groupphoto_status_alter_student_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupphoto',
            old_name='total_number_of_students',
            new_name='total_number_of_students_identified',
        ),
        migrations.AddField(
            model_name='groupphoto',
            name='identified_image',
            field=models.ImageField(default='', upload_to=api.models.upload_boxed_photo),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupphoto',
            name='total_number_of_students_present_in_the_photo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('Done', 'Done'), ('Error', 'Error'), ('In Process', 'In Process')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('CE', 'CE'), ('ME', 'ME'), ('CSE', 'CSE'), ('MEMS', 'MEMS')], default=None, max_length=225, null=True),
        ),
    ]
