# Generated by Django 4.1.7 on 2023-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_total_number_of_students_groupphoto_total_number_of_students_identified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Done', 'Done'), ('Error', 'Error')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('ME', 'ME'), ('MEMS', 'MEMS'), ('CE', 'CE'), ('CSE', 'CSE')], default=None, max_length=225, null=True),
        ),
    ]
