# Generated by Django 4.2.6 on 2023-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_groupphoto_status_alter_student_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image1_encodings',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image2_encodings',
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Error', 'Error'), ('Done', 'Done')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('CE', 'CE'), ('ME', 'ME'), ('EE', 'EE'), ('MEMS', 'MEMS')], default=None, max_length=225, null=True),
        ),
    ]
