# Generated by Django 4.2.6 on 2023-10-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_student_image1_encodings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupphoto',
            name='accuracy',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='groupphoto',
            name='no_of_unidentified_people',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='groupphoto',
            name='status',
            field=models.CharField(blank=True, choices=[('In Process', 'In Process'), ('Done', 'Done'), ('Error', 'Error')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('EE', 'EE'), ('ME', 'ME'), ('CE', 'CE'), ('MEMS', 'MEMS'), ('CSE', 'CSE')], default=None, max_length=225, null=True),
        ),
    ]
