# Use an official Python runtime as a parent image
FROM python:3.11

# Set environment variables
ENV PYTHONUNBUFFERED 1

# Set the working directory to /app
WORKDIR /server

# Copy the current directory contents into the container at /app
COPY . /server

# Install any needed packages specified in requirements.txt
RUN pip install tensorflow --no-cache-dir
RUN pip install aws-shell --no-cache-dir
RUN pip install boto3 --no-cache-dir
RUN pip install celery --no-cache-dir
RUN pip install --no-cache-dir -r requirements.txt
RUN sudo apt-get install -y libgl1-mesa-glx
# Expose port 8000 to the outside world

#run migrations and makemigrations
RUN python manage.py makemigrations
RUN python manage.py migrate

EXPOSE 8000

# Define environment variable
ENV SECRET_KEY django-insecure-&kfn^sxvohx#%&c+hl@_x_40ahcq1^3q45tq)(r1s#6fi=ncbc

# Run app.py when the container launches
CMD ["python", "manage.py", "runserver", "127.0.0.1:8000"]